/* Generated By:JavaCC: Do not edit this line. MiniCTreeConstants.java Version 5.0 */
public interface MiniCTreeConstants
{
  public int JJTZ = 0;
  public int JJTFUNCTION = 1;
  public int JJTARGLIST = 2;
  public int JJT_ARGLIST = 3;
  public int JJTARG = 4;
  public int JJTDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTIDENTLIST = 7;
  public int JJT_ORIDENTLIST = 8;
  public int JJTSTMT = 9;
  public int JJTFORSTMT = 10;
  public int JJTOPTEXPR = 11;
  public int JJTWHILESTMT = 12;
  public int JJTIFSTMT = 13;
  public int JJTELSEPART = 14;
  public int JJTCOMPOUNDSTMT = 15;
  public int JJTSTMTLIST = 16;
  public int JJT_STMTLIST = 17;
  public int JJTEXPR = 18;
  public int JJTRVALUE = 19;
  public int JJT_RVALUE = 20;
  public int JJTCOMPARE = 21;
  public int JJTMAG = 22;
  public int JJT_MAG = 23;
  public int JJTTERM = 24;
  public int JJT_TERM = 25;
  public int JJTFACTOR = 26;


  public String[] jjtNodeName = {
    "Z",
    "Function",
    "ArgList",
    "_ArgList",
    "Arg",
    "Declaration",
    "Type",
    "IdentList",
    "_OrIdentList",
    "Stmt",
    "ForStmt",
    "OptExpr",
    "WhileStmt",
    "IfStmt",
    "ElsePart",
    "CompoundStmt",
    "StmtList",
    "_StmtList",
    "Expr",
    "Rvalue",
    "_Rvalue",
    "Compare",
    "Mag",
    "_Mag",
    "Term",
    "_Term",
    "Factor",
  };
}
/* JavaCC - OriginalChecksum=48e1e7b1aa12c3c23ef1f2da9883f500 (do not edit this line) */
