/* Generated By:JavaCC: Do not edit this line. MiniCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int LESS = 8;
  /** RegularExpression Id. */
  int GREATER = 9;
  /** RegularExpression Id. */
  int LESSEQ = 10;
  /** RegularExpression Id. */
  int GREATEREQ = 11;
  /** RegularExpression Id. */
  int NEQUAL = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int ASSIGN_IDENTIFIER = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int HANDLE_AMBIGUITY = 1;
  /** Lexical state. */
  int GENERATE_ASSIGN = 2;
  /** Lexical state. */
  int GENERATE_ID = 3;
  /** Lexical state. */
  int GENERATE_EQUAL = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"if\"",
    "\"int\"",
    "\"for\"",
    "\"float\"",
    "\"else\"",
    "\"while\"",
    "<NUMBER>",
    "<token of kind 21>",
    "\"=\"",
    "\"==\"",
    "\"\"",
    "\"\"",
    "\"\"",
    "\"\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
